HOST = "irc.chat.twitch.tv"
PORT = 6667
PASS = "oauth:fselnxifw6ebx4akm20rkwy26g8swm"
CLIENT_ID = '4zswqk0crwt2wy4b76aaltk2z02m67'
IDENT = "olyashabot"
#CHANNEL = "wmw_"
CHANNEL = "olyashaa"
#INVITE = 'https://t.me/joinchat/CJeKVUQ-5j6AqVFPx4l0Nw' #wmw invite
INVITE = 'https://t.me/joinchat/FFPy9EQ-5j7BuTnx9jng_g' #olyasha invite
BOT_TOKEN = '560647783:AAFfKjwbNDPnZe4J1rl_KLaeEM7PIafV5Xw' # Your Bot token, create your bot and get token here: https://telegram.me/BotFather
URL_TELE_API = 'https://api.telegram.org/bot%s/' % BOT_TOKEN # Telegram API URL